package main

import (
	config "ambassador/Config"
	database "ambassador/Database"
	routes "ambassador/Routes"
	"fmt"
	"os"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "ambassador/docs"
)

// @title           Golang Ambassador
// @version         2.0
// @description     This is a sample swagger for Fiber
// @termsOfService  http://swagger.io/terms/
// @contact.name    API Support
// @contact.email   fiber@swagger.io
// @license.name    Apache 2.0
// @license.url     http://www.apache.org/licenses/LICENSE-2.0.html
// @host            localhost:4000
// @BasePath        /
// @schemes 		http
func main() {

	// Environment variables
	config.Secrets()

	// Database
	database.Connect()

	app := fiber.New()

	// CORS Configuration
	app.Use(cors.New(cors.Config{
		AllowCredentials: true,
	}))

	// Routes
	routes.Setup(app)

	app.Listen(fmt.Sprintf(":%v", os.Getenv("PORT")))
}
