version: "3.9"

services:
  backend:
    build:
      context: "./Ambassador"
    depends_on:
      - "db"
    ports:
      - "4000:4000"
    volumes:
      - ./Ambassador:/app

  db:
    image: "mysql:8"
    restart: always
    ports:
      - "33066:3306"
    environment:
      MYSQL_DATABASE: ambassador
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
